I have updated documentation of part 4
Arquisoft/viade_en1b pull request #103
Opened 2020-04-03 15:24 UTC by alvarogarinf

I have updated documentation of part 4 taking into account the commen…ts of the previous deriverable, please review this and feel free to comment anything you want to change

2020-04-03 16:43 UTC, alvarogarinf commented
I have also updated the 3.1 diagram table, because its description was not updated

2020-04-03 16:55 UTC, alvarogarinf commented
In point 11 I have added as a technical risk the viade specification

2020-04-04 18:04 UTC, themrcesi approved these changes

2020-04-04 22:25 UTC, lamasumas approved these changes
LGTM

2020-04-08 12:02 UTC, themrcesi requested changes
I would remove the MVC pattern since we actually we don´t follow it 100%.

2020-04-08 12:05 UTC, themrcesi requested changes
> I would remove the MVC pattern since we actually we don´t follow it 100%.

Take a look please.

2020-04-08 12:05 UTC, themrcesi commented on src/docs/04_solution_strategy.adoc
> +| Model-View-Controller | We will use this architectural pattern in order to isolate the presentation layer from the business layer, allowing us to be for flexible | Fast development | MVC architectu
I´d remove this.

2020-04-08 12:05 UTC, themrcesi commented on src/docs/04_solution_strategy.adoc
> +| Coveralls | Hosted analysis tool which provide stadistics about our code coverage | It gives you an stadistical percentage of test coverage of the application |
Change this to CodeCov

2020-04-08 12:05 UTC, themrcesi commented on src/docs/04_solution_strategy.adoc
> +| Code Quality | Write quality code and make it understandable, using the readme for external users understand how the application works and provides information | It gives you a feedback of the code
Change this to Codacy

2020-04-08 14:42 UTC, alvarogarinf commented on src/docs/04_solution_strategy.adoc
> +| Code Quality | Write quality code and make it understandable, using the readme for external users understand how the application works and provides information | It gives you a feedback of the code
I will make those changes

2020-04-10 12:45 UTC, themrcesi approved these changes

2020-04-11 09:03 UTC, themrcesi commented
Ready to merge? @alvarogarinf

2020-04-11 09:05 UTC, merged